"""
Core RAG functions: embed, retrieve, generate, log_result.
Used by both ingest.py (embedding at index time) and app.py (the UI).
"""

import os
import pandas as pd
from dotenv import load_dotenv
import google.generativeai as genai
import chromadb

load_dotenv()

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

if not GOOGLE_API_KEY:
    raise RuntimeError("GOOGLE_API_KEY not set — check your .env file")

genai.configure(api_key=GOOGLE_API_KEY)

# Persistent local vector store — created on first run under ./chroma_db
chroma_client = chromadb.PersistentClient(path="./chroma_db")
collection = chroma_client.get_or_create_collection("wealth_docs")

EMBEDDING_MODEL = "models/gemini-embedding-001"
GENERATION_MODEL = "gemini-3.6-flash"  # gemini-2.5-flash retired for new users; API pointed to this replacement
generation_model = genai.GenerativeModel(GENERATION_MODEL)


def embed(text: str, task_type: str = "RETRIEVAL_DOCUMENT") -> list[float]:
    """
    Embed a piece of text with Gemini.
    task_type: "RETRIEVAL_DOCUMENT" when indexing chunks,
               "RETRIEVAL_QUERY" when embedding a user question.
    """
    result = genai.embed_content(
        model=EMBEDDING_MODEL,
        content=text,
        task_type=task_type,
    )
    return result["embedding"]


def retrieve(query: str, k: int = 5, where: dict | None = None) -> dict:
    """
    Embed the query and pull the top-k most similar chunks from Chroma.
    `where` is an optional Chroma metadata filter, e.g. {"client_id": "CL002"}.
    """
    query_embedding = embed(query, task_type="RETRIEVAL_QUERY")
    return collection.query(
        query_embeddings=[query_embedding],
        n_results=k,
        where=where,
    )


def generate(query: str, retrieved_chunks: list[str]) -> str:
    """
    Answer the query using only the retrieved chunks as context, via Gemini.
    """
    context = "\n\n---\n\n".join(retrieved_chunks)
    prompt = (
        "You are a wealth advisor assistant. Answer only from the provided "
        "context. If the context doesn't contain the answer, say so "
        "explicitly rather than guessing.\n\n"
        f"Context:\n{context}\n\nQuestion: {query}"
    )
    response = generation_model.generate_content(prompt)
    return response.text


def log_result(
    query: str,
    answer: str,
    chunks: list[str],
    metadatas: list[dict],
    path: str = "eval_log.csv",
) -> None:
    """
    Append one exchange in the same column shape as the golden dataset,
    so it can be merged back in for scoring.
    """
    row = {
        "Sample query": query,
        "Response generated by the chatbot": answer,
        "Source(s) referenced by the chatbot": "; ".join(
            m.get("source", "") for m in metadatas
        ),
        "Paragraph(s) referenced by the chatbot": " | ".join(chunks),
    }
    pd.DataFrame([row]).to_csv(
        path, mode="a", header=not os.path.exists(path), index=False
    )