"""
Core RAG functions: embed, retrieve, generate, log_result.
Used by both ingest.py (embedding at index time) and app.py (the UI).
"""

import os
import re
import pandas as pd
from dotenv import load_dotenv
import google.generativeai as genai
import chromadb

load_dotenv()

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

if not GOOGLE_API_KEY:
    raise RuntimeError("GOOGLE_API_KEY not set — check your .env file")

genai.configure(api_key=GOOGLE_API_KEY)

# Persistent local vector store — created on first run under ./chroma_db
chroma_client = chromadb.PersistentClient(path="./chroma_db")
collection = chroma_client.get_or_create_collection("wealth_docs")

EMBEDDING_MODEL = "models/gemini-embedding-001"
GENERATION_MODEL = "gemini-3.6-flash"  # gemini-2.5-flash retired for new users; API pointed to this replacement
generation_model = genai.GenerativeModel(GENERATION_MODEL)


def embed(text: str, task_type: str = "RETRIEVAL_DOCUMENT") -> list[float]:
    """
    Embed a piece of text with Gemini.
    task_type: "RETRIEVAL_DOCUMENT" when indexing chunks,
               "RETRIEVAL_QUERY" when embedding a user question.
    """
    result = genai.embed_content(
        model=EMBEDDING_MODEL,
        content=text,
        task_type=task_type,
    )
    return result["embedding"]


def retrieve(query: str, k: int = 5, where: dict | None = None) -> dict:
    """
    Embed the query and pull the top-k most similar chunks from Chroma.
    `where` is an optional Chroma metadata filter, e.g. {"client_id": "CL002"}.
    """
    query_embedding = embed(query, task_type="RETRIEVAL_QUERY")
    return collection.query(
        query_embeddings=[query_embedding],
        n_results=k,
        where=where,
    )


def format_context(chunks: list[str], metadatas: list[dict]) -> str:
    """Number each chunk and label it with its source, so the model can cite it by name."""
    labeled = []
    for i, (doc, meta) in enumerate(zip(chunks, metadatas), start=1):
        source = meta.get("source", "unknown")
        labeled.append(f"[{i}] Source: {source}\n{doc}")
    return "\n\n".join(labeled)


def generate(query: str, chunks: list[str], metadatas: list[dict]) -> str:
    """
    Answer the query using only the retrieved chunks as context, via Gemini,
    citing the source filename after every claim so the UI can show only the
    files actually used rather than everything that was retrieved.
    """
    context = format_context(chunks, metadatas)
    prompt = (
        "You are a wealth advisor assistant. Answer the question using ONLY "
        "the numbered sources below.\n\n"
        "After every factual claim, cite the source it came from in the "
        "exact format [Source: filename]. If a sentence draws on multiple "
        "sources, cite each one, e.g. [Source: a.pdf, Source: b.pdf]. Only "
        "cite a source if you actually used it — do not cite a source you "
        "didn't draw on.\n\n"
        "If the sources do not contain enough information to answer "
        "confidently, say so explicitly rather than guessing.\n\n"
        f"Sources:\n{context}\n\nQuestion: {query}"
    )
    response = generation_model.generate_content(prompt)
    return response.text


def extract_cited_sources(answer_text: str) -> set[str]:
    """Pull every '[Source: filename]' tag out of the generated answer."""
    return {s.strip() for s in re.findall(r"\[Source:\s*([^\],\]]+)\]", answer_text)}


def filter_relevant(chunks: list[str], metadatas: list[dict], answer_text: str):
    """
    Keep only the retrieved chunks whose source was actually cited in the
    answer. If the model didn't cite anything (formatting slip, or a short
    answer with no claims), fall back to returning everything retrieved
    rather than silently showing nothing.
    """
    cited = extract_cited_sources(answer_text)
    if not cited:
        return chunks, metadatas

    filtered_chunks, filtered_metadatas = [], []
    for chunk, meta in zip(chunks, metadatas):
        if meta.get("source", "") in cited:
            filtered_chunks.append(chunk)
            filtered_metadatas.append(meta)

    if not filtered_chunks:  # citations didn't match any retrieved source name
        return chunks, metadatas
    return filtered_chunks, filtered_metadatas


def log_result(
    query: str,
    answer: str,
    chunks: list[str],
    metadatas: list[dict],
    path: str = "eval_log.csv",
) -> None:
    """
    Append one exchange in the same column shape as the golden dataset,
    so it can be merged back in for scoring.
    """
    row = {
        "Sample query": query,
        "Response generated by the chatbot": answer,
        "Source(s) referenced by the chatbot": "; ".join(
            m.get("source", "") for m in metadatas
        ),
        "Paragraph(s) referenced by the chatbot": " | ".join(chunks),
    }
    pd.DataFrame([row]).to_csv(
        path, mode="a", header=not os.path.exists(path), index=False
    )